### ISSUE TITLE
Train some classes happen below error, for example: 'grid' , 'metal_nut' , 'screw ', 'zipper' etc.

### ISSUE THREAD

**Issue by leolin65** [pankajmishra000/VT-ADL#3]
total test images of good screw are: 41
 --Size of screw train loader: torch.Size([320, 1, 512, 512])--
 --Size of screw test anomaly loader: torch.Size([119, 1, 512, 512])--
 --Size of screw test normal loader: torch.Size([41, 1, 512, 512])--
 --Total Image in screw Validation loader: 20--

Initializing network weights.........

Network training started.....
 ** On entry to SGEMM  parameter number 10 had an illegal value
Traceback (most recent call last):
  File "D:\Code\VT-ADL-master\train.py", line 68, in <module>
    vector, reconstructions = model(j.cuda())
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Code\VT-ADL-master\VT_AE.py", line 50, in forward
    encoded = self.vt(x, self.mask)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Code\VT-ADL-master\student_transformer.py", line 115, in forward
    x = self.patch_to_embedding(x)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by leolin65** [comment]
Others are trainable.

**Comment by pankajmishra000** [comment]
training code edited for the single-channel (grey) images. Now it works fine.
